/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package L164249_LMS;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ammar
 */
public class borrowItemGUI extends javax.swing.JFrame {

private String uid;
private BAL controllor;    
private ArrayList<Book> booklist;
    /**
     * Creates new form borrowItemGUI
     */
    public borrowItemGUI() {
        booklist=new ArrayList<Book>();
        controllor=new BAL();
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.JFrame.HIDE_ON_CLOSE);
            
    }

    public borrowItemGUI(ArrayList<Book> x,String uid) {
       this();
       booklist.addAll(x); 
       setList();
       this.uid=uid;
    }
    
    
    
    
    private void setList(){
      ArrayList<String> temp=new ArrayList<String>();
        for(int i=0;i<booklist.size();++i){
        temp.add(booklist.get(i).toString());
        }
    
         javax.swing.JList<String> tt=new javax.swing.JList(temp.toArray());
          
         jList1=tt;
          
        jScrollPane1.setViewportView(jList1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("ITEMS YOU CHOSE");

        jButton1.setText("BORROW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jButton1)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> bookids=new ArrayList<String>();
        for(int i=0;i<booklist.size();++i){
//        Item it=new Item(
//                booklist.get(i).g,
//                booklist.get(i).get(1),
//                booklist.get(i).get(2),
//                booklist.get(i).get(3),
//                booklist.get(i).get(4)
//        );
        Book it=booklist.get(i);

        
        if(it.getB_QUAN()>0){
          bookids.add(it.getB_ID());
//          int quant=Integer.valueOf(it.getQuan());
//          quant=quant-1;
//          String newq=quant+"";
//          controllor.changeitem(newq,4,it.getId());
        }
        else
            JOptionPane.showMessageDialog(this,"Quantity not Available for"+it.getB_ID());
        }
        
        //prepared list of books now adding it to loan with return and issue dates
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
	//Getting current date
	Calendar cal = Calendar.getInstance();
	//Displaying current date in the desired format
          String issueDate=String.valueOf(sdf.format(cal.getTime()));
	   
	//Number of Days to add
        cal.add(Calendar.MONTH, 1);  
	//Date after adding the days to the current date
	String returnDate = String.valueOf(sdf.format(cal.getTime()));  
	//Displaying the new Date after addition of Days to current date
	//System.out.println("Date after Addition: "+newDate);
            
          
        System.out.println(issueDate);
        System.out.println(returnDate);

        Loan l=new Loan(issueDate,returnDate,this.uid,bookids);
        
        controllor.addloan(l);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
